# Generated by Django 4.2.2 on 2023-06-29 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0003_alter_url_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='count',
            new_name='access_count',
        ),
    ]
